name: Publish Docker Image on Docker hub

on:
  push:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'bitmonero.conf'
  pull_request:
    branches: [ master ]
    paths:
      - 'Dockerfile'
      - 'bitmonero.conf'
  workflow_dispatch:  # Allow manual triggers
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Extract Monero version from Dockerfile
      run: echo "MONERO_VERSION=$(grep 'ENV MONERO_VERSION=' Dockerfile | sed -E 's/ENV MONERO_VERSION=([^ ]+).*/\1/')" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        docker build -t ${{secrets.DOCKER_USER}}/monero-full-node:latest \
                     -t ${{secrets.DOCKER_USER}}/monero-full-node:v${{ env.MONERO_VERSION }} .
    - name: docker Push
      run: docker push --all-tags ${{secrets.DOCKER_USER}}/monero-full-node
